### ISSUE TITLE
How to install Yatai with the latest BentoML version ?

### ISSUE THREAD

**Issue by amelki** [bentoml/Yatai#206]
I would like to test a fix recently pushed in BentoML (https://github.com/bentoml/BentoML/issues/2371).
I could test the fix locally on a running pod, and it seems to work, although I get another error further in the call stack...
In order to test things properly, I would like to re-install / upgrade Yatai on my K8s cluster so that the pods created at deployment time take the proper BentoML version.
Can you tell me how I can do ?

**Comment by amelki** [comment]
Ah, I probably need to rebuild my bento with the proper version. Will give it a try, closing the issue for now

**Comment by amelki** [comment]
OK, I built my bento using version `1.0.0a6.post13+gd77e009` and pushed it to my Yatai server
Looking at the Bento in the Yatai console, I see the correct version, extracted from the manifest:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/5809087/160457313-8e6246ee-3243-4022-bc18-369efb51aa0e.png">

However, when I deploy my bento and log into a pod created, the version of BentoML is 1.0.0a6, so it's not the version I am expecting.
Looking inside the Bento, I see a Dockerfile which references `bentoml/bento-server:1.0.0a6-python3.8-debian-runtime`.
Is it the version used at runtime ? Is there any way I can build a Bento pointing to a docker image from a given build  / version?

**Comment by amelki** [comment]
From what I understand, the version in the Dockerfile comes from here: https://github.com/bentoml/BentoML/blob/6844d1a985bdb74d1042690dea8e3659c425c87c/bentoml/_internal/bento/docker.py#L150. It will always be the latest tag, and never the current main branch... So I guess the only way I can properly test the fix would be that BentoML releases a new version. Is it planned any time soon ?

**Comment by yubozhao** [comment]
@amelki
That's awesome you are trying out a fix with BentoML

To try out a local version of BentoML, you will need to set the envier `BENTOML_BUNDLE_LOCAL_BUILD` to true before build the bento.
What this will do is tell BentoML to:
1. package the local version of BentoML into a wheel file
2. put the wheel file into bento_path/env/python/wheel

When the docker image is building, one of the step is installing the wheel files inside the env. This will install the local version of your BentoML to the docker image.

Let me know if this helpful to get you going.

**Comment by amelki** [comment]
Hi @yubozhao, thanks for your answer.
I tried what you suggested:
  - cloned the BentoML repo
  - created and activated a brand new virtual environment
Then run
```bash 
export BENTOML_BUNDLE_LOCAL_BUILD=True 
cd BentoML
pip3.8 install -e .
pip3.8 install sklearn
```
When I run `bentoml build`, I get the following error:
```
03/28/22 23:44:06 INFO     [cli] BentoML is installed in `editable` model, building BentoML distribution with local BentoML code base. The built wheel file will be included in target bento directory                                                     
~/bentoml-issues/bentomldev/lib/python3.8/site-packages/_distutils_hack/__init__.py:17: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
~/bentoml-issues/bentomldev/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "~/bentoml-issues/bentomldev/bin/bentoml", line 33, in <module>
    sys.exit(load_entry_point('bentoml', 'console_scripts', 'bentoml')())
  File "~/bentoml-issues/bentomldev/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "~/bentoml-issues/bentomldev/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "~/bentoml-issues/bentomldev/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/bentoml-issues/bentomldev/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/bentoml-issues/bentomldev/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "~/bentoml-issues/BentoML/bentoml/_internal/cli/click_utils.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "~/bentoml-issues/BentoML/bentoml/_internal/cli/click_utils.py", line 130, in wrapper
    return_value = func(*args, **kwargs)
  File "~/bentoml-issues/BentoML/bentoml/_internal/cli/click_utils.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "~/bentoml-issues/BentoML/bentoml/_internal/cli/bento_management.py", line 269, in build
    build_bentofile(bentofile, build_ctx=build_ctx, version=version)
  File "~/bentoml-issues/bentomldev/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "~/bentoml-issues/BentoML/bentoml/bentos.py", line 328, in build_bentofile
    bento = Bento.create(
  File "~/bentoml-issues/bentomldev/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "~/bentoml-issues/BentoML/bentoml/_internal/bento/bento.py", line 238, in create
    build_config.python.write_to_bento(bento_fs, build_ctx)
  File "~/bentoml-issues/BentoML/bentoml/_internal/bento/build_config.py", line 273, in write_to_bento
    build_bentoml_whl_to_target_if_in_editable_mode(
  File "~/bentoml-issues/BentoML/bentoml/_internal/bento/build_dev_bentoml_whl.py", line 45, in build_bentoml_whl_to_target_if_in_editable_mode
    from setuptools import sandbox
  File "~/bentoml-issues/bentomldev/lib/python3.8/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "~/bentoml-issues/bentomldev/lib/python3.8/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "~/bentoml-issues/bentomldev/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 72, in do_override
    ensure_local_distutils()
  File "~/bentoml-issues/bentomldev/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py
```

**Comment by yubozhao** [comment]
Can you install dev requirements with the make command `make install-dev-deps` and then try the above steps?

**Comment by amelki** [comment]
I tried, but get the exact same issue...

**Comment by amelki** [comment]
OK, addding `SETUPTOOLS_USE_DISTUTILS=stdlib`, I could build the bento. Testing it right now !

**Comment by amelki** [comment]
OK @yubozhao , I could perform the test !
Thanks for your support, I'm closing the issue.

**Comment by amelki** [comment]
@yubozhao you might want to update the DEVELOPMENT readme and mention that `SETUPTOOLS_USE_DISTUTILS=stdlib` has to be set. 
This seems to be relatively new: https://setuptools.pypa.io/en/latest/history.html#id137

**Comment by yubozhao** [comment]
@amelki Thank you for the heads up. 🙏🏼 I will update the documentation in BentoML
